version: "3"
services:
    client:
        container_name: "fofm_app_client"
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - /app/node_modules
            - ./client:/app
        stdin_open: true
    nginx:
        container_name: fofm_app_nginx
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "3000:80"
    server:
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        container_name: fofm_app_server
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        volumes:
            - /app/node_modules
            - ./server:/app

    mongo:
        container_name: fofm_app_mongo
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./data/db
        