version: "3"
services:
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        stdin_open: true
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "3000:80"
    server:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        container_name: fofm_app_server
        volumes:
            - /fofm_app/node_modules
            - ./server:/fofm_app
        environment:
            - MONGO_URI="mongodb+srv://bis92:164487s2@boilerplate.2wgwr.mongodb.net/friendOptimizedforme?retryWrites=true&w=majority"